on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-stable:
    uses: ublue-os/ucore/.github/workflows/reusable-build.yml@main
    secrets: inherit
    with:
      coreos_version: stable
