---
on:
  push: {}
  workflow_dispatch: {}
jobs:
  iso:
    uses: ublue-os/isogenerator/.github/workflows/iso.yml@main
    with:
      IMAGE_VERSION: stable
      IMAGE_ARCH: x86_64
      IMAGE_NAME: corehost
      IMAGE_REPO: ghcr.io/ii
      VARIANT: coreos
